import type { PropertyDeclaration } from 'lit'

/**
 * Boolean converter that accepts both HTML boolean syntax (`disabled`) and the
 * explicit string form (`disabled="false"`). This is useful for templates
 * generated by server-side renderers and keeps the public attributes intuitive.
 */
export const booleanAttribute: Pick<PropertyDeclaration, 'converter'>['converter'] = {
  fromAttribute: (value: string | null) => value !== null && value !== 'false',
  toAttribute: (value: boolean) => (value ? '' : null),
}
