// Components
export { MacConfigProvider } from './components/config-provider/mac-config-provider'
export { MacButton } from './components/button/mac-button'
export { MacCard } from './components/card/mac-card'
export { MacInput } from './components/input/mac-input'
export { MacSelect } from './components/select/mac-select'
export type { SelectOption, OptionGroup } from './components/select/mac-select'
export { MacDesktopIcon } from './components/desktop-icon/mac-desktop-icon'
export { MacDesktop } from './components/desktop/mac-desktop'
export type { DesktopIconData } from './components/desktop/mac-desktop'
export { MacDockItem } from './components/dock/mac-dock-item'
export { MacDock } from './components/dock/mac-dock'
export { MacDialog } from './components/dialog/mac-dialog'
export { MacGroupButton } from './components/group-button/mac-group-button'
export type { GroupButtonItem } from './components/group-button/mac-group-button'
export { MacDropdown } from './components/dropdown/mac-dropdown'
export type { DropdownItem } from './components/dropdown/mac-dropdown'
export { MacTextEllipsis } from './components/text-ellipsis/mac-text-ellipsis'
export { MacRating } from './components/rating/mac-rating'
export { MacDescriptions, MacDescriptionItem } from './components/descriptions/mac-descriptions'
export type { DescriptionItem } from './components/descriptions/mac-descriptions'
export { MacNumberAnimation } from './components/number-animation/mac-number-animation'
export { MacTabs, MacTabPane } from './components/tabs/mac-tabs'
export type { TabItem } from './components/tabs/mac-tabs'
export { MacDrawer } from './components/drawer/mac-drawer'
export { MacPopconfirm } from './components/popconfirm/mac-popconfirm'

// Base class (for extension)
export { BaseElement } from './internal/base-element'

// Styles
export { sharedStyles } from './styles/shared-styles'
export { themeTokens } from './styles/theme'
